// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.jsRemoteUIClient = (function(_super) {
    __extends(jsRemoteUIClient, _super);

    function jsRemoteUIClient() {
      _ref = jsRemoteUIClient.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    jsRemoteUIClient.prototype.initialize = function() {
      this.socket = io.connect('http://127.0.0.1', {
        port: 8081,
        rememberTransport: false
      });
      this.broadcastReceiver = new jsRemoteUIBroadcastReceiver({
        socket: this.socket,
        port: 25748
      });
      this.headerView = new HeaderView({
        model: this.broadcastReceiver
      });
      jQuery('body').append(this.headerView.el);
      return jQuery('body').append('<hr/>');
    };

    jsRemoteUIClient.prototype.update = function() {};

    jsRemoteUIClient.prototype.draw = function() {};

    return jsRemoteUIClient;

  })(Backbone.Model);

}).call(this);
