// Generated by CoffeeScript 1.6.3
(function() {
  this.jsRemoteUIMessage = (function() {
    function jsRemoteUIMessage(rawMessage) {
      this.source = rawMessage || {};
    }

    jsRemoteUIMessage.prototype.params = function() {
      return (this.source.data || [])[2];
    };

    jsRemoteUIMessage.prototype.messageLine = function() {
      return this.params()[0];
    };

    jsRemoteUIMessage.prototype.messageText = function() {
      return this.messageLine() || "";
    };

    jsRemoteUIMessage.prototype.type = function() {
      if (/^SEND SPA (\w+)/.test(this.messageText())) {
        return "SENDSPA";
      }
      if (/^SEND (\w+) (\w+)/.test(this.messageText())) {
        return "SENDPARAM";
      }
      if (/^REQU/.test(this.messageText())) {
        return "REQU";
      }
    };

    jsRemoteUIMessage.prototype.sendSpaName = function() {
      if (this.type() === "SENDSPA") {
        return this.params()[1];
      }
    };

    jsRemoteUIMessage.prototype.sendSpaId = function() {
      var result;
      result = /^SEND SPA (\w+) - (\d+)/.exec(this.messageText());
      if (result) {
        return result[2];
      }
      return null;
    };

    jsRemoteUIMessage.prototype.paramType = function() {
      return /^SEND (\w+) (\w+)/.exec(this.messageText())[1];
    };

    jsRemoteUIMessage.prototype.paramName = function() {
      return /^SEND (\w+) (\w+)/.exec(this.messageText())[2];
    };

    jsRemoteUIMessage.prototype.paramValue = function() {
      return this.params()[1];
    };

    jsRemoteUIMessage.prototype.paramMinValue = function() {
      return this.params()[2];
    };

    jsRemoteUIMessage.prototype.paramMaxValue = function() {
      return this.params()[3];
    };

    return jsRemoteUIMessage;

  })();

}).call(this);
