// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Session = (function(_super) {
    __extends(Session, _super);

    function Session() {
      _ref = Session.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Session.prototype.initialize = function() {
      this.sender = new oscSender({
        socket: this.get('socket'),
        host: this.get('remote').get('ip'),
        port: this.get('remote').get('port')
      });
      return this.requestCompleteUpdate();
    };

    Session.prototype.requestCompleteUpdate = function() {
      return this.sender.send('REQU');
    };

    return Session;

  })(Backbone.Model);

  this.SessionsCollection = (function(_super) {
    __extends(SessionsCollection, _super);

    function SessionsCollection() {
      _ref1 = SessionsCollection.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    SessionsCollection.prototype.model = Session;

    return SessionsCollection;

  })(Backbone.Collection);

}).call(this);
