// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.GroupsListView = (function(_super) {
    __extends(GroupsListView, _super);

    function GroupsListView() {
      _ref = GroupsListView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GroupsListView.prototype.tagName = "div";

    GroupsListView.prototype.className = "groups";

    GroupsListView.prototype.initialize = function() {
      var _this = this;
      this.groupViews = [];
      return this.collection.on('add', function(group) {
        var groupView;
        groupView = new GroupView({
          model: group
        });
        _this.$el.append(groupView.el);
        return _this.groupViews.push(groupView);
      });
    };

    return GroupsListView;

  })(Backbone.View);

  this.GroupView = (function(_super) {
    __extends(GroupView, _super);

    function GroupView() {
      _ref1 = GroupView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    GroupView.prototype.tagName = "div";

    GroupView.prototype.className = "group";

    GroupView.prototype.initialize = function() {
      this.$el.append('<h2>' + this.model.get('name') + '</h2>');
      this.paramsView = new ParamsListView({
        collection: this.model.params
      });
      return this.$el.append(this.paramsView.el);
    };

    return GroupView;

  })(Backbone.View);

  this.ParamsListView = (function(_super) {
    __extends(ParamsListView, _super);

    function ParamsListView() {
      _ref2 = ParamsListView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    ParamsListView.prototype.tagName = "div";

    ParamsListView.prototype.className = "params";

    ParamsListView.prototype.initialize = function() {
      var _this = this;
      this.views = [];
      return this.collection.on('add', function(param) {
        var view;
        view = new ParamView({
          model: param
        });
        _this.$el.append(view.el);
        return _this.views.push(view);
      });
    };

    return ParamsListView;

  })(Backbone.View);

  this.ParamView = (function(_super) {
    __extends(ParamView, _super);

    function ParamView() {
      _ref3 = ParamView.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    ParamView.prototype.tagName = "div";

    ParamView.prototype.className = "param";

    ParamView.prototype.initialize = function() {
      return this.$el.append('<h3>' + this.model.get('name') + ': ' + this.model.get('value') + '</h3>');
    };

    return ParamView;

  })(Backbone.View);

}).call(this);
